# Generated by Django 4.1.7 on 2023-05-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='category_discription',
            new_name='category_description',
        ),
    ]
