# Generated by Django 4.1.7 on 2023-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credapp', '0002_rename_category_discription_categorydb_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='poductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
