# Generated by Django 4.1.7 on 2023-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credapp', '0003_poductdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='poductdb',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product-img'),
        ),
    ]
