# Generated by Django 4.2.1 on 2023-06-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='cartImage',
        ),
    ]
